name: publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  push-to-registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secret.Docker_USERNAME}}
          password: $ {{secret.Docker_PASSWORD}}
      - name: Extra meta information
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: askurr/git-action
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{steps.meta.output.tags}}



